version: "3.3"

services:
  app:
    container_name: api
    bbuild:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    build: .
    volumes:
      - ".:/usr/app"
      - /usr/app/node_modules
    depends_on:
      - db
    links:
      - db
    ports:
      - 3000:3000
  db:
    image: "mongo"
    container_name: api-mongodb
    ports:
      - 27017:27017

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
