version: '3.3'

services:
  app:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - '.:/usr/app'
      - /usr/app/node_modules
    depends_on:
      - db
    links:
      - db
    ports:
      - 3000:3000
  db:
    image: 'mongo'
    container_name: api-mongodb
    ports:
      - 27017:27017
